import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFonts from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const alfa = localFonts({
  // src: "./public/fonts/AlfaSlabOne-Regular.ttf",
  src: "../../public/fonts/AlfaSlabOne-Regular.ttf",
  variable: "--font-custom",
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Underated",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${alfa.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
